# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b74eb7507546d83b5dcd1d493041e182c2b0d3c2fc9a2b21323fe81ded179ade012a07f262270771ba8ec2954c294fa0cf7d166b14a22d52236637938a0df527

test:
  secret_key_base: 5d571115a9f6e710cb5463bea367c3515157f26025082ffe34304c06e66dee16e2da413a2a00ecc125a7d60011d56784d04dfad198a389dc70ee8dafe51b7a57
  # Action Mailer Opts
  action_mailer_host_name: "example.com"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # Action Mailer Opts
  action_mailer_host_name: <%= ENV["ACTION_MAILER_HOST_NAME"] %>
